=== protokol/kredential-manager/apps/backend/src/schemas/ebsi-vid/natural-person/2023-08/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "PID as W3C VC",
  "description": "The schema defines a structure for W3C VC PID",
  "type": "object",
  "properties": {
    "@context": {
      "oneOf": [
        {
          "const": "https://www.w3.org/ns/credentials/v2"
        },
        {
          "description": "Semantic context for the issued credential. First element MUST be https://www.w3.org/ns/credentials/v2",
          "type": "array",
          "items": {
            "type": "string",
            "format": "uri"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "id": {
      "description": "Globally unique identifier for the issued credential. It can be a UUID or another globally unique identifier. document_number as per ARF",
      "type": "string",
      "format": "uri"
    },
    "type": {
      "description": "Full type chain, used to identify the credential base types",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "issuer": {
      "description": "DID of the credential issuer. issuing_authority as per ARF",
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "object",
          "required": ["id"],
          "properties": {
            "id": {
              "description": "DID of the credential issuer",
              "type": "string",
              "format": "uri"
            },
            "issuingCountry": {
              "description": "issuing_country as per ARF. ISO 2-letter code",
              "$ref": "#/$defs/nationality"
            }
          }
        }
      ]
    },
    "validFrom": {
      "description": "Defines the earliest point when the credential becomes valid. issuance_date as per ARF",
      "type": "string",
      "format": "date-time"
    },
    "validUntil": {
      "description": "Defines the latest point when the credential ceases to be valid. expiry_date as per ARF",
      "type": "string",
      "format": "date-time"
    },
    "credentialSubject": {
      "$ref": "#/$defs/credentialSubjectPID"
    },
    "credentialStatus": {
      "description": "Defines suspension and/or revocation details for the issued credential. Further redefined by the type extension",
      "type": "object",
      "properties": {
        "id": {
          "description": "Exact identity for the credential status",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines the revocation type extension",
          "type": "string"
        }
      },
      "required": ["id", "type"]
    },
    "credentialSchema": {
      "description": "One or more schemas that validate the Verifiable Credential.",
      "anyOf": [
        {
          "$ref": "#/$defs/credentialSchema"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/credentialSchema"
          }
        }
      ]
    },
    "termsOfUse": {
      "anyOf": [
        {
          "$ref": "#/$defs/termsOfUse"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/termsOfUse"
          }
        }
      ]
    },
    "evidence": {
      "description": "Contains information about the process which resulted in the issuance of the credential",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "If present, it MUST contain a URL that points to where more information about this instance of evidence can be found.",
            "type": "string"
          },
          "type": {
            "description": "Defines the evidence type extension",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["type"]
      }
    }
  },
  "required": [
    "@context",
    "id",
    "type",
    "issuer",
    "validFrom",
    "credentialSubject",
    "credentialSchema"
  ],
  "$defs": {
    "credentialSubjectPID": {
      "type": "object",
      "properties": {
        "credentialSubject": {
          "description": "Defines additional information about the subject that is described by the Verifiable ID",
          "type": "object",
          "properties": {
            "id": {
              "description": "Defines the DID of the subject that is described by the Verifiable Attestation. unique_id as per ARF",
              "type": "string",
              "format": "uri"
            },
            "familyName": {
              "description": "Defines current family name(s) of the credential subject. family_name as per ARF",
              "type": "string"
            },
            "firstName": {
              "description": "Defines current first name(s) of the credential subject. given_name as per ARF",
              "type": "string"
            },
            "familyNameAtBirth": {
              "description": "Defines family name(s) of the credential subject at birth. family_name_birth as per ARF",
              "type": "string"
            },
            "firstNameAtBirth": {
              "description": "Defines first name(s) of the credential subject at birth. given_name_birth as per ARF",
              "type": "string"
            },
            "dateOfBirth": {
              "description": "Defines date of birth of the credential subject. birth_date as per ARF",
              "type": "string",
              "format": "date"
            },
            "yearOfBirth": {
              "description": "Defines the year of birth of the credential subject. age_birth_year as per ARF",
              "type": "string",
              "format": "date"
            },
            "ageOverNN": {
              "description": "age_over_NN as per ARF.",
              "type": "boolean"
            },
            "ageInYears": {
              "description": "age_in_years as per ARF.",
              "type": "number"
            },
            "personalIdentifier": {
              "description": "Defines the unique national identifier of the credential subject (constructed by the sending Member State in accordance with the technical specifications for the purposes of cross-border identification and which is as persistent as possible in time). Alternative non-cryptographic identifier.  unique_id or administrative_identifier as per ARF",
              "type": "string"
            },
            "placeOfBirth": {
              "description": "Defines the place where the credential subject is born. birth_place, _country, _state, _city as per ARF",
              "$ref": "#/$defs/address"
            },
            "currentAddress": {
              "description": "Defines the current address of the credential subject. resident_address as per ARF",
              "$ref": "#/$defs/address"
            },
            "gender": {
              "description": "Defines the gender of the credential subject. Note: enumeration should be extended to capture are recognised genders. gender as per ARF",
              "type": "string",
              "enum": ["male", "female", "other"]
            },
            "nationality": {
              "description": "One or more nationalities. Recognised vocabulary must be used to express the nationalities. nationality as per ARF",
              "oneOf": [
                {
                  "$ref": "#/$defs/nationality"
                },
                {
                  "type": "array",
                  "items": {
                    "$ref": "#/$defs/nationality"
                  },
                  "minItems": 1
                }
              ]
            }
          },
          "required": [
            "id",
            "familyName",
            "firstName",
            "dateOfBirth",
            "personalIdentifier"
          ]
        }
      }
    },
    "nationality": {
      "type": "string",
      "enum": [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ]
    },
    "address": {
      "description": "Postal Address as per schema.org with additional Full Address property.",
      "type": "object",
      "properties": {
        "addressCountry": {
          "description": "Defines the country of residence of the credential subject. MUST be two-letter ISO 3166-1 alpha-2 country code.",
          "type": "string"
        },
        "addressRegion": {
          "description": "Defines the address region of residence of the credential subject. MUST be ISO 3166-2 code",
          "type": "string"
        },
        "addressLocality": {
          "description": "The locality in which the street address is, and which is in the region. For example, Mountain View.",
          "type": "string"
        },
        "postalCode": {
          "description": "Defines the postal code of residence of the credential subject",
          "type": "string"
        },
        "streetAddress": {
          "description": "The street address. For example, 1600 Amphitheatre",
          "type": "string"
        },
        "fullAddress": {
          "description": "The complete address written as a string. https://semiceu.github.io/Core-Person-Vocabulary/releases/2.1.0/",
          "type": "string"
        }
      }
    },
    "credentialSchema": {
      "description": "Contains information about the credential schema on which the issued credential is based",
      "type": "object",
      "properties": {
        "id": {
          "description": "References the credential schema stored on the Trusted Schemas Registry (TSR)",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines credential schema type",
          "type": "string",
          "enum": ["JsonSchema", "ShaclValidator2017"]
        }
      },
      "required": ["id", "type"]
    },
    "termsOfUse": {
      "description": "Contains the terms under which the issued credential was issued",
      "type": "object",
      "properties": {
        "id": {
          "description": "Contains a URL that points to where more information about this instance of terms of use can be found.",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "description": "Defines the type extension",
          "type": "string"
        }
      },
      "required": ["type"]
    }
  }
}

=== protokol/kredential-manager/apps/backend/src/schemas/ebsi-attestation/2023-09/examples/verifiable-authorisation-onboard.json
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "id": "urn:uuid:08e26d22-8dca-4558-9c14-6e7aa7275b9b",
  "type": [
    "VerifiableCredential",
    "VerifiableAttestation",
    "VerifiableAuthorisationToOnboard"
  ],
  "issuer": "did:ebsi:ziDnioxYYLW1a3qUbqTFz4W",
  "validFrom": "2023-01-01T00:00:00Z",
  "validUntil": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:ebsi:zdPj1GPXjfERXxXPE1YTYdJ"
  },
  "credentialSchema": {
    "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v2/schemas/0x23039e6356ea6b703ce672e7cfac0b42765b150f63df78e2bd18ae785787f6a2",
    "type": "JsonSchema"
  }
}

=== protokol/kredential-manager/apps/backend/src/schemas/ebsi-vid/natural-person/2023-08/examples/example-be.json
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "id": "https://example.com/credentials/456",
  "type": ["VerifiableCredential", "VerifiablePID"],
  "issuer": "did:ebsi:123",
  "validFrom": "2023-09-01T00:00:00Z",
  "validUntil": "2024-08-31T23:59:59Z",
  "credentialSubject": {
    "id": "did:key:123",
    "familyName": "Dubois",
    "firstName": "Sophie",
    "dateOfBirth": "1985-05-20",
    "personalIdentifier": "987654321",
    "placeOfBirth": {
      "addressCountry": "BE",
      "addressRegion": "BRU",
      "addressLocality": "Brussels"
    },
    "currentAddress": {
      "addressCountry": "BE",
      "addressRegion": "VBR",
      "addressLocality": "Leuven",
      "postalCode": "3000",
      "streetAddress": "456 Elm Ave",
      "fullAddress": "456 Elm Ave, Leuven, VBR 3000, Belgium"
    },
    "gender": "female",
    "nationality": ["BE"]
  },
  "credentialStatus": {
    "id": "https://api.ebsi.eu/csl",
    "type": "DynamicSLBloomFilter2023"
  },
  "credentialSchema": {
    "id": "https://api.ebsi.eu/tsr",
    "type": "JsonSchema"
  }
}

=== protokol/kredential-manager/apps/backend/src/schemas/ebsi-trust-model/2023-10/examples/TI-accredited-to-attest.json
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "id": "urn:uuid:8568b525-a24e-4bc0-9d97-6a8459ec0130",
  "type": [
    "VerifiableCredential",
    "VerifiableAttestation",
    "VerifiableTrustModel",
    "VerifiableAccreditationToAttest"
  ],
  "issuer": "did:ebsi:zdPj1GPXjfERXxXPE1YTYdJ",
  "validFrom": "2021-11-01T00:00:00Z",
  "validUntil": "2024-06-22T14:11:44Z",
  "credentialSubject": {
    "id": "did:ebsi:zzRmkLPGaFZ9oUrZ6tRF4mk",
    "reservedAttributeId": "111551f6f18c63a10d4b2ca8f41bb16b77f4877630d90b4977d4fed311fc2eaf",
    "permissionFor": [
      {
        "schemaId": "https://api-test.ebsi.eu/trusted-schemas-registry/v3/schemas/zHgbyz9ajVuSProgyMhsiwpcp8g8aVLFRNARm51yyYZp6",
        "types": [
          "VerifiableCredential",
          "VerifiableAttestation",
          "WorkCertificate"
        ],
        "jurisdiction": "https://publications.europa.eu/resource/authority/atu/FIN"
      }
    ]
  },
  "termsOfUse": {
    "type": "AccreditationPolicy",
    "rootAuthorisation": "https://api-test.ebsi.eu/trusted-issuers-registry/v5/issuers/did:ebsi:zvHWX359A3CvfJnCYaAiAde/attributes/60ae46e4fe9adffe0bc83c5e5be825aafe6b5246676398cd1ac36b8999e088a8",
    "parentAccreditation": "https://api-test.ebsi.eu/trusted-issuers-registry/v4/issuers/did:ebsi:zdPj1GPXjfERXxXPE1YTYdJ/attributes/061e750db05d75b024a78f291ae5d4e7d71c71d270384e08d7853f4cbc3b2c75"
  },
  "credentialStatus": {
    "id": "https://api-test.ebsi.eu/trusted-issuers-registry/v4/issuers/did:ebsi:zzRmkLPGaFZ9oUrZ6tRF4mk/attributes/111551f6f18c63a10d4b2ca8f41bb16b77f4877630d90b4977d4fed311fc2eaf",
    "type": "EbsiAccreditationEntry"
  },
  "credentialSchema": {
    "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v3/schemas/zCSHSDwrkkd32eNjQsMCc1h8cnFaxyTXP5ByozyVQXZoH",
    "type": "JsonSchema"
  }
}

=== protokol/kredential-manager/apps/backend/src/schemas/type-extensions/termsOfUse/AttestationPolicy/2023-10/examples/accredited-work-certificate.json
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd",
  "type": ["VerifiableCredential", "VerifiableAttestation", "WorkCertificate"],
  "issuer": {
    "id": "did:ebsi:ziDnioxYYLW1a3qUbqTFz4W",
    "type": "organisation",
    "legalName": "Company ABC",
    "domainName": "https://company.abc"
  },
  "validFrom": "2023-01-01T00:00:00Z",
  "validUntil": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbnTvvSLAcNJvfNeLNuB9Y3Mbhus5btx3CBNknmhSStgGbqhMkqfWNSYZ5Vd1A8xQdD948jQSEjShYE1SFe1wZSgsw5S4v6sfHVV2p6waDwh9hCjdWdjFUo3nyU1rYLbuZxg",
    "familyName": "Wonderland",
    "firstName": "Alice",
    "startDate": "2023-01-01T00:00:00Z",
    "endDate": "2024-01-01T00:00:00Z",
    "listOfOccupations": [
      {
        "startDate": "2023-01-01T00:00:00Z",
        "endDate": "2023-06-01T00:00:00Z",
        "occupationalCategory": "15-1252.00"
      },
      {
        "startDate": "2023-06-01T00:00:00Z",
        "endDate": "2024-01-01T00:00:00Z",
        "occupationalCategory": "15-1254.00"
      }
    ]
  },
  "termsOfUse": {
    "type": "AttestationPolicy",
    "rootAuthorisation": "https://api-test.ebsi.eu/trusted-issuers-registry/v5/issuers/did:ebsi:zvHWX359A3CvfJnCYaAiAde/attributes/60ae46e4fe9adffe0bc83c5e5be825aafe6b5246676398cd1ac36b8999e088a8",
    "parentAccreditation": "https://api-test.ebsi.eu/trusted-issuers-registry/v4/issuers/did:ebsi:zdPj1GPXjfERXxXPE1YTYdJ/attributes/061e750db05d75b024a78f291ae5d4e7d71c71d270384e08d7853f4cbc3b2c75"
  },
  "credentialSchema": [
    {
      "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v3/schemas/zHgbyz9ajVuSProgyMhsiwpcp8g8aVLFRNARm51yyYZp6",
      "type": "JsonSchema"
    },
    {
      "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v3/schemas/zwTFt3rYS78X1rSpqdoH7KuqhftS1sEEteQsNtjcH8mD",
      "type": "JsonSchema"
    }
  ]
}

=== protokol/kredential-manager/apps/backend/src/schemas/ebsi-delegated-authorisation/2023-09/examples/1-didebsi-tao-authorises.json
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "id": "urn:uuid:b720ddfb-3107-4b75-a31c-9467f17b8c48",
  "type": [
    "VerifiableCredential",
    "VerifiableAttestation",
    "VerifiableMandate"
  ],
  "issuer": "did:ebsi:zvHWX359A3CvfJnCYaAiAde",
  "validFrom": "2023-01-01T00:00:00Z",
  "validUntil": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:ebsi:zdPj1GPXjfERXxXPE1YTYdJ",
    "permission": {
      "scope": "timestamp_write",
      "claims": [
        "timestampHashes",
        "timestampRecordHashes",
        "timestampVersionHashes",
        "insertRecordOwner",
        "revokeRecordOwner",
        "timestampRecordVersionHashes",
        "appendRecordVersionHashes",
        "detachRecordVersionHash",
        "insertRecordVersionInfo",
        "sendSignedTransaction"
      ]
    },
    "maxDelegationCount": 2
  },
  "termsOfUse": [
    {
      "id": "https://api-test.ebsi.eu/trusted-issuers-registry/../..xyz",
      "type": "IssuanceCertificate"
    }
  ],
  "credentialSchema": [
    {
      "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v3/schemas/0x..",
      "type": "JsonSchema"
    }
  ]
}

=== protokol/kredential-manager/apps/backend/src/schemas/ebsi-muti-uni-pilot/work-certificate/2023-09/examples/simple.json
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd",
  "type": ["VerifiableCredential", "VerifiableAttestation", "WorkCertificate"],
  "issuer": {
    "id": "did:ebsi:ziDnioxYYLW1a3qUbqTFz4W",
    "type": "organisation",
    "legalName": "Company ABC",
    "domainName": "https://company.abc"
  },
  "validFrom": "2023-01-01T00:00:00Z",
  "validUntil": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "id": "did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9KbnTvvSLAcNJvfNeLNuB9Y3Mbhus5btx3CBNknmhSStgGbqhMkqfWNSYZ5Vd1A8xQdD948jQSEjShYE1SFe1wZSgsw5S4v6sfHVV2p6waDwh9hCjdWdjFUo3nyU1rYLbuZxg",
    "familyName": "Wonderland",
    "firstName": "Alice",
    "startDate": "2023-01-01T00:00:00Z",
    "endDate": "2024-01-01T00:00:00Z",
    "listOfOccupations": [
      {
        "startDate": "2023-01-01T00:00:00Z",
        "endDate": "2023-06-01T00:00:00Z",
        "occupationalCategory": "15-1252.00"
      },
      {
        "startDate": "2023-06-01T00:00:00Z",
        "endDate": "2024-01-01T00:00:00Z",
        "occupationalCategory": "15-1254.00"
      }
    ]
  },
  "credentialSchema": {
    "type": "JsonSchema",
    "id": "https://link.to.json.schema"
  }
}
